# Generated by Django 3.2 on 2021-04-15 15:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRecord',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('value', multiselectfield.db.fields.MultiSelectField(choices=[('pan', 'Pan'), ('aadhaar', 'Aadhaar'), ('college', 'College'), ('corporate', 'Corporate'), ('dl', 'DL'), ('voter', 'Voter'), ('passport', 'Passport'), ('local', 'Local'), ('other', 'Other')], default=list, max_length=59)),
                ('pick_first', models.BooleanField(default=False)),
            ],
        ),
    ]
