# Generated by Django 3.2 on 2021-04-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppOne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrecord',
            name='JSONObject',
            field=models.JSONField(default=dict),
        ),
    ]
