# Generated by Django 3.2 on 2021-04-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppOne', '0002_roomrecord_jsonobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrecord',
            name='JSONObject',
            field=models.TextField(default='{}'),
        ),
    ]
