# Generated by Django 3.2 on 2021-04-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppOne', '0003_alter_roomrecord_jsonobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomrecord',
            name='JSONObject',
        ),
    ]
