# Generated by Django 3.2 on 2021-04-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppOne', '0004_remove_roomrecord_jsonobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRecordOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled', models.BooleanField()),
                ('partially_filled', models.BooleanField()),
                ('trigger', models.CharField(max_length=20)),
                ('parameters', models.TextField()),
            ],
        ),
    ]
