# Generated by Django 3.2 on 2021-04-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppOne', '0005_roomrecordoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrecordoutput',
            name='trigger',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
