# Generated by Django 3.2 on 2021-04-16 13:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myAppOne', '0007_agerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='agerecord',
            name='pick_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agerecord',
            name='value',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(-1, -1), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35)], default=list, max_length=98),
        ),
    ]
