# Generated by Django 3.2 on 2021-04-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppOne', '0008_auto_20210416_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRecordOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled', models.BooleanField()),
                ('partially_filled', models.BooleanField()),
                ('trigger', models.CharField(blank=True, max_length=20)),
                ('parameters', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='agerecord',
            name='constraint_value',
            field=models.BooleanField(default=False),
        ),
    ]
