# Generated by Django 3.2 on 2021-04-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppOne', '0009_auto_20210416_2242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgeRecord',
            new_name='AgeRecordInput',
        ),
        migrations.RenameModel(
            old_name='RoomRecord',
            new_name='RoomRecordInput',
        ),
    ]
