# Generated by Django 3.2 on 2021-04-16 21:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myAppOne', '0011_auto_20210417_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agerecordinput',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agerecordinput',
            name='value',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(-1, -1), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35)], default=list, max_length=65),
        ),
        migrations.AlterField(
            model_name='roomrecordinput',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
